package com.databricks.jdbc.model.telemetry.latency;

public enum OperationType {
  TYPE_UNSPECIFIED,
  CREATE_SESSION,
  DELETE_SESSION,
  EXECUTE_STATEMENT,
  EXECUTE_STATEMENT_ASYNC,
  CLOSE_STATEMENT,
  CANCEL_STATEMENT,
  LIST_TYPE_INFO,
  LIST_CATALOGS,
  LIST_SCHEMAS,
  LIST_TABLES,
  LIST_TABLE_TYPES,
  LIST_COLUMNS,
  LIST_FUNCTIONS,
  LIST_PRIMARY_KEYS,
  LIST_IMPORTED_KEYS,
  LIST_EXPORTED_KEYS,
  LIST_CROSS_REFERENCES
}
